on: push

jobs:
  npm-audit-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: miyajan/npm-audit-pr@first-commit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
